NAME = "Random"

CARDS = [
   "Scrubs",
   "Band Of Brothers",
   "Weeds",
   "House",
   "Chuck",
   "Futurama",
   "NCIS",
   "Mr Robot",
   "Dr Who",
   "Flight of the Concords",
   "The West Wing",
   "Suits",
   "Psych",
   "Rick and Morty",
   "CSI Cyber",
   "Community",
   "Top Gear",
   "Silicon Valley",
   "Lost",
   "Breaking Bad",
   "Game of Thrones",
   "Ballers",
   "The Wire",
   "The Sopranos",
   "Sherlock",
   "Firefly",
   "True Detective",
   "Pokemon",
   "Stranger Things ",
   "Dexter",
   "House of Cards",
   "Arrested Developement",
   "Narcos",
   "Twin Peaks",
   "Seinfeld",
   "Friends",
   "Freaks and Geeks",
   "The Simpsons ",
   "Gravity Falls",
   "South Parks",
   "Archer",
   "The Office",
   "The X Files",
   "Louie",
   "Parks and Recreation",
   "Better off Ted",
   "The IT Crowd",
   "Modern Family",
   "Entourage",
   "How I Met Your Mother",
   "The Walking Dead",
   "Star Trek",
   "24",
   "Homeland",
   "Monk",
   "White Collar ",
   "That 70's Show",
   "South Park",
   "Gossip Girls",
   "Its Always Sunny In Philadelphia",
   "Mad Men",
   "Brooklyn 99",
   "Archer",
   "Friday Night Lights",
   "The Man In The High Castle",
   "Empire",
   "Sex And The City",
   "Girls",
   "30 Rock",
   "The League",
   "M*A*S*H",
   "Lie to Me",
   "Royal Pains",
   "Burn Notice",
   "The Fresh Prince of Belair",
   "Adventure Time ",
   "3rd Rock From the Sun  ",
   "Rocket Power",
   "Fairly Odd Parents",
   "Spongebob",
   "Ed, Edd and Eddy",
   "Johny Bravo",
   "Invader Zim",
   "Jimmy Neutron",
   "Rugrats",
   "Wild Thornberries",
   "Hey Arnold!",
   "Drake and Josh",
   "Suite Life of Zack and Cody",
   "Recess",
   "Doug",
   "Blues Clues",
   "Catdog",
   "Angry Beavers",
   "Bob the Builder",
   "Teletubies ",
   "Chowder",
   "Thomas the Tank Engine",
   "Wallace and Gromit",
   "Pokemon",
   "Yu-Gi-Oh",
   "Agents of Shields",
   "Gilmore Girls",
   "The Munsters",
   "Dexters Lab",
   "Brickleberry",
   "Malcom in the Middle",
   "AMerican Horror Story",
   "Minority Report",
   "Bobs Burgers",
   "Orange is the New Black",
   "NCIS",
   "Chopped",
   "Good Eats",
   "Sex and the City",
   "Wilfred",
   "Scooby Doo",
   "Degrassi",
   "Video Game Highschool",
   "Twilight Zone",
   "Goosebumps",
   "Veep",
   "The Newsroom",
   "Empire",
   "Numbers",
   "CyberChaser"
]